### ISSUE TITLE
Compiling problem OSX 10.11 and 10.12

### ISSUE THREAD

**Issue by mi-ga** [monkeyswarm/MobMuPlatEditor#13]
In between I wanted to update my MobMuPlatEditor and the xcode doesn't compile neither on 10.11 nor 10.12 saying that there is Quicktime.h missing. Would it be possible to include in the packages compiled versions so less experienced people like me could download a ready to use application?

**Comment by monkeyswarm** [comment]
The compiled applications are available via a link to a .zip on the front page of www.mobmuplat.com. I will add a link in the readme.
