### ISSUE TITLE
Opening existing pd patch onto MobMuPlatEditor editor not working

### ISSUE THREAD

**Issue by billyjoker** [monkeyswarm/MobMuPlatEditor#15]
Hi, i'm opening MobMuPlatEditor.jar and then i load a pd file choosing from "Main Pd File", but the pd file is never shown in the editor, what is the right way to do this? Thx

**Comment by monkeyswarm** [comment]
The MobMuPlat Editor does not open the pd file. The file specified in the "Main Pd File" merely tells MobMuPlat, when it loads this interface file, which pure data file to open underneath it. You open Pure Data, and the file you wish to use, separately. Please see the instructions on www.mobmuplat.com (either on the front page or on the "rough documentation" page).

**Comment by billyjoker** [comment]
So i can not use an external pd taken from sites like patchstorage and importing with MobMuplat? I've read the docs but i still have no clear. Thanks again.

**Comment by monkeyswarm** [comment]
You can use any pure data patch which uses only Pd vanilla objects.
You can either
1) Create a custom interface in the MMP editor, and then add the relevant communication in the Pd patch (e.g. create a slider "/mySlider" in the interface, and then add
[receive fromGUI]
|
[list trim]
|
[route /mySlider]
to get the value in the patch.

OR

2) You can use (or add) "native" Pd gui elements (sliders/buttons/etc) to the .pd file and just open the .pd file in MobMuPlat (go to documents and turn on "show all files" to show .pd files and render the Pd patch on screen). Note that this method is more experimental than #1 and may have bugs, please contact me if the patch doesn't work as expected.
