### ISSUE TITLE
Problem(s) compiling under Windows 7

### ISSUE THREAD

**Issue by dfkettle** [monkeyswarm/MobMuPlatEditor#19]
I'm trying to compile MobMuPlatEditor (which I downloaded today from this repository) using Java v18.0.1.1 from Oracle, under Windows 7 SP1 (64-bit). However, there were 32 errors and 100 warnings issued. I've attached a screen shot and a file containing the error and warning messages. Should I be using a different version of Java to compile?

![MobMuPlatEditor](https://user-images.githubusercontent.com/8409615/177003146-487f4258-2837-4390-b2cc-8b42450ebad0.jpg)

[errors.txt](https://github.com/monkeyswarm/MobMuPlatEditor/files/9033068/errors.txt)

**Comment by monkeyswarm** [comment]
Note that precompiled binaries are available as described in the README; you don't need to be compiling yourself unless you wish to modify the code.

The errors are for missing dependencies; I do not know the details of how java classpath may have changed since I wrote the initial compilation command. Do you actually have the gson package in the expected location?

**Comment by dfkettle** [comment]
> Note that precompiled binaries are available as described in the README; you don't need to be compiling yourself unless you wish to modify the code.

I couldn't find any precompiled binaries for Windows. Which README, the one for MobMuPlat or MobMuPlat Editor?

> 
> The errors are for missing dependencies; I do not know the details of how java classpath may have changed since I wrote the initial compilation command. Do you actually have the gson package in the expected location?

Is this the right location?

![Image1](https://user-images.githubusercontent.com/8409615/177009785-4f04301c-c0a1-4c93-a098-dec901f08916.jpg)

**Comment by dfkettle** [comment]
OK, I changed the compile command to the following and the gson lib was found. Note that I copied-and-pasted the original command from the README file (for MobMuPlat Editor. You might want to update it.

`javac -cp lib/gson-2.2.4.jar @sources.txt`

I'm still getting 100 warning messages about deprecated methods, though. I assume it's OK to ignore them, but it seems they're "marked for removal".

[errors.txt](https://github.com/monkeyswarm/MobMuPlatEditor/files/9033367/errors.txt)

**Comment by monkeyswarm** [comment]
The readme for this repo: "If you just want the compiled applications, go to http://www.mobmuplat.com/ and download the development package .zip file, linked in the "setup" section. More info on usage, including sample files, is in that package."

**Comment by dfkettle** [comment]
Thanks, I found it and it's working, so I guess I don't need to compile it. Although I'm not sure why anyone would download the source from this repo unless they wanted to compile it.
