### ISSUE TITLE
pdwrapper.pd does not seem to work

### ISSUE THREAD

**Issue by pavallin** [monkeyswarm/MobMuPlatEditor#2]
Using pd-extended 0.43-4 on Windows 7.
The window displays a series of red warning, such as :

<!DOCTYPE: no such object
s=400": no such object
s=400": no such object
padding:0: no such object
display:inline"><input: no such object
": no such object
s=40": no such object
padding:0: no such object
display:inline"><input: no such object
": no such object
padding:0: no such object
display:inline"><input: no such object
": no such object
padding:0: no such object
display:inline"><input: no such object
": no such object
padding:0: no such object
display:inline"><input: no such object
": no such object
protocol_type=clone">: no such object
protocol_type=clone">: no such object
protocol_type=clone">: no such object
s=48": no such object
s=48": no such object
</td>: no such object

followed by several
</td>: no such object

and some weird
float: no such object

The patch can't be displayed so far, I wasn't able to try and figure out what the problem is. 

If I'm doing something wrong, feel free to leave a comment :)

pavallin.

**Comment by monkeyswarm** [comment]
PdWrapper is for Pd vanilla (.46 and above), not Pd-extended.
