### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by dfkettle** [monkeyswarm/MobMuPlatEditor#21]
Please consider adding horizontal and vertical radio button groups, like in PureData. I could use a menu instead, but sometimes a group of radio buttons is easier to use, and it would make it easier to migrate existing patches to MobMuPlat.

**Comment by monkeyswarm** [comment]
You can recreate the behavior of radio buttons with existing MobMuPlat controls, either 
a) by using N toggle buttons, or
b) an Nx1 grid of buttons
and then add a message in the patch which clears the other buttons / cells when a member is toggled on (and also does not un-set the value if the current selection is tapped)

**Comment by dfkettle** [comment]
I realize that, I was just being lazy. That would require more coding in PD (although not a lot). If you're keeping a list of requests for future enhancements, please keep this in mind.
