### ISSUE TITLE
A question, maybe an issue, I'm not sure

### ISSUE THREAD

**Issue by dfkettle** [monkeyswarm/MobMuPlatEditor#22]
I'm not sure if what I'm trying to do is supposed to work or not. It works in MobMuPlatEditor, but when I copy the files to my tablet, it doesn't. What I want to do is define a label on top of a menu, so I can display the current menu selection without using an extra screen real estate. I'm not sure if you're supposed to be able to define a widget on top of another widget, but in the editor, there are buttons labelled "Bring Forward" and "Bring Backward", so I thought I'd try it.

In the editor, when I pick a selection in the menu, the label gets updated correctly. But on my tablet, it doesn't. Is this kind of behaviour supposed to work, or am I trying to do something that isn't supported?

(A nice enhancement would be to have the menu widget display the value of the current selection. But if I can get this to work, that's good enough for me.)

Attached are the two files (renamed because Github won't let me upload them with the original file names).

[menu-test - mmp.txt](https://github.com/monkeyswarm/MobMuPlatEditor/files/9126298/menu-test.-.mmp.txt)
[menu-test - pd.txt](https://github.com/monkeyswarm/MobMuPlatEditor/files/9126299/menu-test.-.pd.txt)

**Comment by monkeyswarm** [comment]
You are using iemlib in your patch. MobMuPlat only supports vanilla, without any externally compiled libraries. If you open the 'console' tab in the mobile app, I am assuming you will see (as I do):
"splitfilename /
error:...couldn't create"

I would also note that Pd does not handle strings (and OSC addresses) with slashes very well. I would start with 'simple' OSC addresses (only a leading slash, no multiple slashes) and see if you can get it working from there.

**Comment by dfkettle** [comment]
> You are using iemlib in your patch. MobMuPlat only supports vanilla, without any externally compiled libraries. If you open the 'console' tab in the mobile app, I am assuming you will see (as I do): "splitfilename / error:...couldn't create"
> 
Thanks. I didn't even know about the console tab. Now I see the message.

> I would also note that Pd does not handle strings (and OSC addresses) with slashes very well. I would start with 'simple' OSC addresses (only a leading slash, no multiple slashes) and see if you can get it working from there.

I've written other patches in PD using [oscformat] and [oscparse] to communicate with a Python script and had no problem with  OSC addresses containing multiple slashes. But I couldn't use [oscparse] here because the OSC message had already been parsed by 'PdWrapper'. However, I think that part of my patch works (at least in the editor; it's only failing on my tablet). What's the point of using OSC if it doesn't handle OSC messages properly? You might just as well use [netsend] and [netreceive] and not bother with OSC. Anyway, once I figure out a fix for the lack of [splitfilename], I'll test it again. I wanted to group all menu messages under '/menu/...', button messages under '/btn/...', etc., so I could use [route] to split them into separate streams, to make my patch a little cleaner. Are you saying that hierarchical OSC addresses don't work?

**Comment by dfkettle** [comment]
I came up with a replacement for [splitfilename]. It's a little more complicated, but it seems to work, both on the tablet and in the editor. Attached is the PD file if you're interested (no change to the MMP file). There doesn't seem to be any problem with multiple slashes in the OSC address, MobMuPlat seems to handle them properly, both sending and receiving (although I haven't tested it on an iPhone or tablet, since I don't own one).

[menu-test - pd.txt](https://github.com/monkeyswarm/MobMuPlatEditor/files/9126836/menu-test.-.pd.txt)

**Comment by monkeyswarm** [comment]
Glad you found a workaround. Yes, I meant that the Pd objects ([oscformat] and [oscparse]) don't handle hierarchical addresses with slashes (they use spaces as separators) when passing them around as pd messages within a patch. Communication to/from MobMuPlat should be compliant with the OSC spec otherwise.
