### ISSUE TITLE
Is [pdcontrol] supported?

### ISSUE THREAD

**Issue by dfkettle** [monkeyswarm/MobMuPlatEditor#23]
Hi again!

I'm using [pdcontrol] to find the directory in which MobMuPlat is installed (so I can load a data file from a subdirectory named 'data'). Attached is a screen print of the subpatch that loads the file. It works in the editor, but on my tablet, I'm getting a "couldn't create" error. Isn't [pdcontrol] part of vanilla PD? Is there some reason I can't use it?

Thanks again.

![Image1](https://user-images.githubusercontent.com/8409615/180202410-3d3fc308-205b-4a3f-8d5b-9e219129b47b.jpg)

**Comment by dfkettle** [comment]
P.S. I removed [dir(, [pdcontrol] and [makefilename], but [openpanel] doesn't seem to work either. I'm not getting any error message in the Pd console, but nothing happens. I checked the permissions for the MobMuPlat app and it has access to local files. Isn't it possible to open and read local files using [openpanel] and [read(?

**Comment by monkeyswarm** [comment]
pdcontrol, openpanel, makefilename, and some other objects (I believe [key] and [keyup]), and a variety of system messages, are all directly tied to a desktop OS environment system/GUI hooks, and are not expected to work on mobile or on other embedded platforms. 

MobMuPlat uses libpd to load and interact with Pd, I suggest you look there for more information about various limitations: https://github.com/libpd/libpd 

Also, please file MobMuPlat issues in the app issue tracker, not this tracker for the editor applications: https://github.com/monkeyswarm/MobMuPlat/issues

**Comment by dfkettle** [comment]
So is there no way to read or write text files? I don't see any information there about its limitations, without going through the source code.

**Comment by monkeyswarm** [comment]
The [text] object, and reading and writing files, still works. The pd file will write/read paths as relative to the location of the patch itself, so you should be able to use [read foo.txt( and [write foo.txt( messages in the path (and use subdirectories).
