### ISSUE TITLE
Pages > 1 are shown wrong.

### ISSUE THREAD

**Issue by MarioMey** [monkeyswarm/MobMuPlatEditor#5]
This is how the pages are shown in Editor. There's something wrong from the page 2. Look how I had to arrange the elements to be correctly shown in tablet.

Page 1:
![pantallazo-circo3d_mobmuplat mmp-1](https://cloud.githubusercontent.com/assets/4954109/12790432/fc3822a8-ca80-11e5-8e3d-b10fdc58c26c.png)

Page 2:
![pantallazo-circo3d_mobmuplat mmp](https://cloud.githubusercontent.com/assets/4954109/12790406/d9bc65cc-ca80-11e5-9416-df1d2323aa8a.png)

Page 3:
![pantallazo-circo3d_mobmuplat mmp-2](https://cloud.githubusercontent.com/assets/4954109/12790443/0c6a5286-ca81-11e5-893e-2cfb51ffcdf6.png)

Page 4:
![pantallazo-circo3d_mobmuplat mmp-3](https://cloud.githubusercontent.com/assets/4954109/12790451/1878c2c4-ca81-11e5-8399-56dcd3737f6c.png)

**Comment by monkeyswarm** [comment]
Fixed in upcoming release, thanks for pointing it out.
