### ISSUE TITLE
build instructions

### ISSUE THREAD

**Issue by umlaeute** [monkeyswarm/MobMuPlatEditor#8]
please provide some build instructions to create `MobMuPlatEditor`.

i'm not a regular eclipse user (i guess this is what you are using), and I cannot really load the MobMuPlatEditor-Java _project_ with my limited skill-set.

**Comment by JRSV** [comment]
is there any help available for this?

**Comment by monkeyswarm** [comment]
Added notes in README, make sure you pull the most recent commits since I change some resource loading.
